# Generated by Django 5.0.2 on 2024-03-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=100)),
                ('catname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.category')),
            ],
            options={
                'db_table': 'Subcategory',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('expDateTime', models.DateField()),
                ('transaction_type', models.CharField(choices=[('expense', 'expense'), ('income', 'income')], max_length=50)),
                ('status', models.CharField(choices=[('cleared', 'cleared'), ('uncleared', 'uncleared'), ('void', 'void')], max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.subcategory')),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
    ]
