# Generated by Django 5.0.2 on 2024-03-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_accounttype_currencytype_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
