# Generated by Django 5.0.2 on 2024-03-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0006_rename_goalname_expense_goal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='goal_name',
            new_name='goal',
        ),
        migrations.AlterModelTable(
            name='goal',
            table='goal',
        ),
    ]
