# Generated by Django 5.0.2 on 2024-03-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0008_account_day_account_incmome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='incmome',
            new_name='income',
        ),
    ]
